import { NextResponse } from 'next/server';
import { csrfValid } from '@/lib/csrf';
import { webAuthSession } from '@/lib/server-auth';
const apiBase = process.env.PACHI_API_URL ?? 'http://localhost:3001';
const maxUploadBytes = 15 * 1024 * 1024;

export async function GET(_request: Request, context: { params: Promise<{ id: string }> }) { const { auth } = await webAuthSession(); if (!auth) return NextResponse.json({ error: 'authentication_required' }, { status: 401 }); const { id } = await context.params; const response = await fetch(`${apiBase}/v1/account/listing-drafts/${id}/media`, { headers: { authorization: `Bearer ${auth.accessToken}` }, cache: 'no-store' }); return NextResponse.json(await response.json(), { status: response.status }); }
export async function POST(request: Request, context: { params: Promise<{ id: string }> }) { const { cookie, auth } = await webAuthSession(); if (!auth) return NextResponse.json({ error: 'authentication_required' }, { status: 401 }); if (!(await csrfValid(request, cookie.csrfToken))) return NextResponse.json({ error: 'csrf_rejected' }, { status: 403 }); const declaredLength = Number(request.headers.get('content-length') ?? 0); if (declaredLength > maxUploadBytes) return NextResponse.json({ error: 'photo_too_large' }, { status: 413 }); const body = await readLimitedBody(request); if (!body) return NextResponse.json({ error: 'photo_too_large' }, { status: 413 }); const { id } = await context.params; const response = await fetch(`${apiBase}/v1/account/listing-drafts/${id}/media`, { method: 'POST', headers: { authorization: `Bearer ${auth.accessToken}`, 'content-type': request.headers.get('content-type') ?? '', 'content-length': String(body.byteLength) }, body }); return NextResponse.json(await response.json(), { status: response.status }); }

async function readLimitedBody(request: Request): Promise<ArrayBuffer | null> { if (!request.body) return new ArrayBuffer(0); const reader = request.body.getReader(); const chunks: Uint8Array[] = []; let total = 0; while (true) { const { done, value } = await reader.read(); if (done) break; total += value.byteLength; if (total > maxUploadBytes) { await reader.cancel(); return null; } chunks.push(value); } const body = new Uint8Array(total); let offset = 0; for (const chunk of chunks) { body.set(chunk, offset); offset += chunk.byteLength; } return body.buffer; }
