export type OrganizationType = 'REAL_ESTATE_AGENCY' | 'PROPERTY_MANAGEMENT_COMPANY' | 'CORPORATE_PROPERTY_OWNER' | 'OTHER_APPROVED_PROVIDER';
export type SupportedOrganizationType = Exclude<OrganizationType, 'OTHER_APPROVED_PROVIDER'>;
export type OrganizationState = 'DRAFT' | 'ACTIVE' | 'RESTRICTED' | 'SUSPENDED' | 'CLOSED';
export type OrganizationRole = 'OWNER' | 'ADMIN' | 'LISTING_MANAGER' | 'AGENT' | 'ANALYST';
export type OrdinaryOrganizationRole = 'LISTING_MANAGER' | 'AGENT' | 'ANALYST';
export type OrganizationMembershipState = 'INVITED' | 'ACTIVE' | 'SUSPENDED' | 'REVOKED' | 'DECLINED' | 'EXPIRED';
export type OrganizationSummary = {
  id: string;
  public_name: string;
  organization_type: OrganizationType;
  state: OrganizationState;
  version: number;
  provider_account_id: string;
  business_verification: 'NOT_VERIFIED';
  publication_eligible: false;
  public_contact: { phone: string | null };
  membership: { id: string; role: OrganizationRole; state: OrganizationMembershipState; version: number };
  created_at: string;
};
export type OrganizationMember = {
  id: string;
  organization_id: string;
  user_id: string;
  role: OrganizationRole;
  state: OrganizationMembershipState;
  version: number;
  activated_at: string | null;
  revoked_at: string | null;
};
export type OrganizationInvitation = {
  id: string;
  organization_id: string;
  organization_public_name: string;
  role: OrdinaryOrganizationRole;
  state: 'INVITED' | 'ACTIVE' | 'DECLINED' | 'REVOKED' | 'EXPIRED';
  version: number;
  expires_at: string;
  created_at: string;
  membership_id: string;
  can_respond: boolean;
};
export type OrganizationListResponse = { organizations: OrganizationSummary[]; next_cursor: string | null };
export type OrganizationMemberListResponse = { members: OrganizationMember[]; next_cursor: string | null };
export type OrganizationInvitationListResponse = { invitations: OrganizationInvitation[]; next_cursor: string | null };
export type OrganizationCreateRequest = { legal_name: string; public_name: string; organization_type: SupportedOrganizationType; public_phone_opt_in: boolean };
export type OrganizationInvitationCreateRequest = { recipient_phone: string; role: OrdinaryOrganizationRole; expected_version: number };
export type OrganizationInvitationRespondRequest = { token: string; expected_version: number };
export type OrganizationVersionRequest = { expected_version: number };
export type OrganizationMemberRoleRequest = { role: OrdinaryOrganizationRole; expected_version: number };
