'use client';

import { useEffect, useState } from 'react';

type Session = { authenticated: boolean; accountState?: string; participationAllowed?: boolean; csrfToken?: string };
type Property = { id: string; property_type: string; region: string; city: string; neighborhood: string; relationship_type: string };
type Draft = { id: string; property_id: string; purpose: string; title: string | null; description: string | null; amount_minor: number | null; pricing_period: string; negotiable: boolean; deposit_amount_minor: number | null; advance_months: number | null; minimum_lease_months: number | null; utilities_included: boolean | null; service_charge_amount_minor: number | null; weekly_amount_minor: number | null; minimum_nights: number | null; guest_limit: number | null; check_in_time: string | null; check_out_time: string | null; cleaning_fee_minor: number | null; available_from: string | null; currency: string; publication_status: string; version: number };

export default function ProviderWorkspace() {
  const [session, setSession] = useState<Session | null>(null); const [properties, setProperties] = useState<Property[]>([]); const [drafts, setDrafts] = useState<Draft[]>([]); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const [property, setProperty] = useState({ property_type: 'APARTMENT', region: 'Littoral', city: 'Douala', neighborhood: '', relationship_type: 'OWNER' });
  const [draft, setDraft] = useState({ property_id: '', purpose: 'RENT', title: '', description: '', amount_minor: '', pricing_period: 'MONTHLY', negotiable: false, deposit_amount_minor: '', advance_months: '', minimum_lease_months: '', utilities_included: '', service_charge_amount_minor: '', weekly_amount_minor: '', minimum_nights: '', guest_limit: '', check_in_time: '', check_out_time: '', cleaning_fee_minor: '', available_from: '' });
  const [editingDraftId, setEditingDraftId] = useState<string | null>(null);
  const [csrf, setCsrf] = useState('');

  async function load() { const s = await fetch('/api/session', { cache: 'no-store' }).then((r) => r.json() as Promise<Session>); setSession(s); setCsrf(s.csrfToken ?? ''); if (s.authenticated && s.participationAllowed) { const [p, d] = await Promise.all([fetch('/api/account/properties').then((r) => r.json() as Promise<{ properties: Property[] }>), fetch('/api/account/listing-drafts').then((r) => r.json() as Promise<{ drafts: Draft[] }>)]); setProperties(p.properties ?? []); setDrafts(d.drafts ?? []); } }
  useEffect(() => { void load().catch(() => setError('The provider workspace could not be loaded.')); }, []);

  async function createProperty(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); setMessage(''); try { const response = await fetch('/api/account/properties', { method: 'POST', headers: { 'content-type': 'application/json', 'x-csrf-token': csrf }, body: JSON.stringify(property) }); if (!response.ok) throw new Error(); setMessage('Property draft saved.'); await load(); } catch { setError('Property could not be saved. Check the required fields.'); } finally { setBusy(false); } }
  async function openDraft(id: string) { setError(''); try { const response = await fetch(`/api/account/listing-drafts/${id}`, { cache: 'no-store' }); if (!response.ok) throw new Error(); const saved = await response.json() as Draft; setEditingDraftId(saved.id); setDraft({ property_id: saved.property_id, purpose: saved.purpose, title: saved.title ?? '', description: saved.description ?? '', amount_minor: saved.amount_minor?.toString() ?? '', pricing_period: saved.pricing_period, negotiable: saved.negotiable, deposit_amount_minor: saved.deposit_amount_minor?.toString() ?? '', advance_months: saved.advance_months?.toString() ?? '', minimum_lease_months: saved.minimum_lease_months?.toString() ?? '', utilities_included: saved.utilities_included === null ? '' : String(saved.utilities_included), service_charge_amount_minor: saved.service_charge_amount_minor?.toString() ?? '', weekly_amount_minor: saved.weekly_amount_minor?.toString() ?? '', minimum_nights: saved.minimum_nights?.toString() ?? '', guest_limit: saved.guest_limit?.toString() ?? '', check_in_time: saved.check_in_time?.slice(0, 5) ?? '', check_out_time: saved.check_out_time?.slice(0, 5) ?? '', cleaning_fee_minor: saved.cleaning_fee_minor?.toString() ?? '', available_from: saved.available_from ?? '' }); } catch { setError('That private draft could not be reopened.'); } }
  async function saveDraft(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); setMessage(''); const numeric = (value: string) => value === '' ? undefined : Number(value); const updatedNumeric = (value: string) => value === '' ? null : numeric(value); const maybeTime = (value: string) => editingDraftId && !value ? null : value || undefined; const payload = { ...draft, amount_minor: editingDraftId ? updatedNumeric(draft.amount_minor) : numeric(draft.amount_minor), deposit_amount_minor: editingDraftId ? updatedNumeric(draft.deposit_amount_minor) : numeric(draft.deposit_amount_minor), advance_months: editingDraftId ? updatedNumeric(draft.advance_months) : numeric(draft.advance_months), minimum_lease_months: editingDraftId ? updatedNumeric(draft.minimum_lease_months) : numeric(draft.minimum_lease_months), utilities_included: draft.utilities_included === '' ? editingDraftId ? null : undefined : draft.utilities_included === 'true', service_charge_amount_minor: editingDraftId ? updatedNumeric(draft.service_charge_amount_minor) : numeric(draft.service_charge_amount_minor), weekly_amount_minor: editingDraftId ? updatedNumeric(draft.weekly_amount_minor) : numeric(draft.weekly_amount_minor), minimum_nights: editingDraftId ? updatedNumeric(draft.minimum_nights) : numeric(draft.minimum_nights), guest_limit: editingDraftId ? updatedNumeric(draft.guest_limit) : numeric(draft.guest_limit), check_in_time: maybeTime(draft.check_in_time), check_out_time: maybeTime(draft.check_out_time), cleaning_fee_minor: editingDraftId ? updatedNumeric(draft.cleaning_fee_minor) : numeric(draft.cleaning_fee_minor), available_from: editingDraftId && !draft.available_from ? null : draft.available_from || undefined }; try { const response = await fetch(editingDraftId ? `/api/account/listing-drafts/${editingDraftId}` : '/api/account/listing-drafts', { method: editingDraftId ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json', 'x-csrf-token': csrf }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error(); const saved = await response.json() as Draft; setEditingDraftId(saved.id); setMessage('Private listing draft saved.'); await load(); await openDraft(saved.id); } catch { setError('Listing draft could not be saved. Check the offering terms and property.'); } finally { setBusy(false); } }
  function startNewDraft() { setEditingDraftId(null); setDraft({ property_id: '', purpose: 'RENT', title: '', description: '', amount_minor: '', pricing_period: 'MONTHLY', negotiable: false, deposit_amount_minor: '', advance_months: '', minimum_lease_months: '', utilities_included: '', service_charge_amount_minor: '', weekly_amount_minor: '', minimum_nights: '', guest_limit: '', check_in_time: '', check_out_time: '', cleaning_fee_minor: '', available_from: '' }); }

  if (!session) return <main className="shell"><section className="panel"><h1>Provider workspace</h1><p className="muted">Loading account state.</p></section></main>;
  if (!session.authenticated) return <main className="shell"><section className="panel"><h1>Provider workspace</h1><p className="muted">Sign in before opening provider tools.</p><a className="primary" href="/api/auth/login?returnTo=/provider">Continue with Pachi</a></section></main>;
  if (!session.participationAllowed) return <main className="shell"><section className="panel"><h1>Provider workspace</h1><p className="muted">Phone ownership is required before provider drafts are available.</p><a className="secondary" href="/">Return to account</a></section></main>;
    return <main className="workspace"><nav><a href="/provider" className="active">Overview</a><a href="#properties">Properties</a><a href="#drafts">Listing drafts</a><a href="/">Return to account</a></nav><header><p className="eyebrow">PACHI / PROVIDER WORKSPACE</p><h1>Prepare your inventory</h1><p className="muted">Private drafts are saved to your provider account. Nothing here publishes a listing.</p></header>{message && <p className="successMessage">{message}</p>}{error && <p className="error" role="alert">{error}</p>}<section id="properties" className="workspaceGrid"><div className="tool"><h2>New property</h2><form onSubmit={(event) => { void createProperty(event); }}>
<label>Property type<select value={property.property_type} onChange={(e) => setProperty({ ...property, property_type: e.target.value })}><option>APARTMENT</option><option>HOUSE</option><option>ROOM</option><option>LAND</option><option>COMMERCIAL</option></select></label>
<label>Region<select value={property.region} onChange={(e) => setProperty({ ...property, region: e.target.value })}><option>Littoral</option><option>Southwest</option></select></label>
<label>City<input value={property.city} onChange={(e) => setProperty({ ...property, city: e.target.value })} required /></label>
<label>Neighborhood<input value={property.neighborhood} onChange={(e) => setProperty({ ...property, neighborhood: e.target.value })} required /></label>
<button className="primary" disabled={busy}>Save property</button>
</form></div><div className="tool"><h2>Your properties</h2>{properties.length ? <ul>{properties.map((item) => <li key={item.id}><strong>{item.property_type}</strong><span>{item.city} · {item.neighborhood}</span></li>)}</ul> : <p className="muted">No properties saved yet.</p>}</div></section><section id="drafts" className="workspaceGrid"><div className="tool">
    <h2>{editingDraftId ? 'Edit private listing draft' : 'New private listing draft'}</h2>
    {editingDraftId && <button className="linkButton" type="button" onClick={startNewDraft}>Create another draft</button>}
    <form onSubmit={(event) => { void saveDraft(event); }}>
      <label>Property<select value={draft.property_id} disabled={Boolean(editingDraftId)} onChange={(event) => setDraft({ ...draft, property_id: event.target.value })} required><option value="">Choose a property</option>{properties.map((item) => <option key={item.id} value={item.id}>{item.city} · {item.neighborhood}</option>)}</select></label>
      <label>Transaction<select value={draft.purpose} disabled={Boolean(editingDraftId)} onChange={(event) => { const purpose = event.target.value; setDraft({ ...draft, purpose, pricing_period: purpose === 'RENT' ? 'MONTHLY' : purpose === 'SALE' ? 'TOTAL' : 'NIGHTLY', deposit_amount_minor: '', advance_months: '', minimum_lease_months: '', utilities_included: '', service_charge_amount_minor: '', weekly_amount_minor: '', minimum_nights: '', guest_limit: '', check_in_time: '', check_out_time: '', cleaning_fee_minor: '' }); }}><option>RENT</option><option>SALE</option><option>SHORT_LET</option></select></label>
      <label>Title<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label>
      <label>Description<textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} rows={4} /></label>
      <label>Amount in XAF<input inputMode="numeric" value={draft.amount_minor} onChange={(event) => setDraft({ ...draft, amount_minor: event.target.value })} /></label>
      <label>Pricing period<select value={draft.pricing_period} disabled><option>MONTHLY</option><option>TOTAL</option><option>NIGHTLY</option></select></label>
      <label><input type="checkbox" checked={draft.negotiable} onChange={(event) => setDraft({ ...draft, negotiable: event.target.checked })} /> Negotiable</label>
      {draft.purpose === 'RENT' && <><label>Deposit in XAF<input inputMode="numeric" value={draft.deposit_amount_minor} onChange={(event) => setDraft({ ...draft, deposit_amount_minor: event.target.value })} /></label><label>Advance months<input inputMode="numeric" value={draft.advance_months} onChange={(event) => setDraft({ ...draft, advance_months: event.target.value })} /></label><label>Minimum lease months<input inputMode="numeric" value={draft.minimum_lease_months} onChange={(event) => setDraft({ ...draft, minimum_lease_months: event.target.value })} /></label><label>Utilities included<select value={draft.utilities_included} onChange={(event) => setDraft({ ...draft, utilities_included: event.target.value })}><option value="">Not specified</option><option value="true">Yes</option><option value="false">No</option></select></label><label>Service charge in XAF<input inputMode="numeric" value={draft.service_charge_amount_minor} onChange={(event) => setDraft({ ...draft, service_charge_amount_minor: event.target.value })} /></label></>}
      {draft.purpose === 'SHORT_LET' && <><label>Weekly rate in XAF<input inputMode="numeric" value={draft.weekly_amount_minor} onChange={(event) => setDraft({ ...draft, weekly_amount_minor: event.target.value })} /></label><label>Minimum nights<input inputMode="numeric" value={draft.minimum_nights} onChange={(event) => setDraft({ ...draft, minimum_nights: event.target.value })} /></label><label>Guest limit<input inputMode="numeric" value={draft.guest_limit} onChange={(event) => setDraft({ ...draft, guest_limit: event.target.value })} /></label><label>Check-in<input type="time" value={draft.check_in_time} onChange={(event) => setDraft({ ...draft, check_in_time: event.target.value })} /></label><label>Check-out<input type="time" value={draft.check_out_time} onChange={(event) => setDraft({ ...draft, check_out_time: event.target.value })} /></label><label>Cleaning fee in XAF<input inputMode="numeric" value={draft.cleaning_fee_minor} onChange={(event) => setDraft({ ...draft, cleaning_fee_minor: event.target.value })} /></label></>}
      <label>Available from<input type="date" value={draft.available_from} onChange={(event) => setDraft({ ...draft, available_from: event.target.value })} /></label>
      <button className="primary" disabled={busy}>{editingDraftId ? 'Save draft changes' : 'Save private draft'}</button>
    </form>
  </div>
  <div className="tool"><h2>Saved drafts</h2>{drafts.length ? <ul>{drafts.map((item) => <li key={item.id}><button className="draftItem" type="button" onClick={() => { void openDraft(item.id); }}><strong>{item.title || 'Untitled draft'}</strong><span>{item.purpose} · {item.amount_minor ?? 'No amount yet'} {item.currency} · {item.publication_status} · v{item.version}</span></button></li>)}</ul> : <p className="muted">No private drafts saved yet.</p>}</div>
</section></main>;
}
