import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import { exportJWK, generateKeyPair, SignJWT } from 'jose';
import { NestFactory } from '@nestjs/core';
import { createDatabase, ProviderVerificationStore, type StaffPrincipal } from '@pachi/database';

if (!process.env.DATABASE_TEST_URL && process.env.CI === 'true') throw new Error('DATABASE_TEST_URL is required for property HTTP integration tests');
const integrationTest = process.env.DATABASE_TEST_URL ? test : test.skip;

void integrationTest('property and private listing draft HTTP workflow is eligible, ownership-scoped, and versioned', async () => {
  const databaseUrl = process.env.DATABASE_TEST_URL;
  assert.ok(databaseUrl);
  const { privateKey, publicKey } = await generateKeyPair('RS256');
  const jwk = await exportJWK(publicKey); jwk.kid = 'property-test-key';
  const jwksServer = createServer((_request, response) => { response.setHeader('content-type', 'application/json'); response.end(JSON.stringify({ keys: [jwk] })); });
  await new Promise<void>((resolve) => jwksServer.listen(0, '127.0.0.1', resolve));
  const jwksAddress = jwksServer.address(); assert.ok(jwksAddress && typeof jwksAddress === 'object');
  const issuer = 'http://127.0.0.1/property-test';
  process.env.NODE_ENV = 'test'; process.env.DATABASE_URL = databaseUrl; process.env.COGNITO_ISSUER = issuer; process.env.COGNITO_JWKS_URI = `http://127.0.0.1:${jwksAddress.port}/jwks`; process.env.COGNITO_CLIENT_IDS = 'property-test-client'; process.env.AUTH_REQUIRED_SCOPES = 'pachi/account';
  const { AppModule } = await import('./app.module.js');
  const { authDatabaseClient } = await import('./auth.module.js');
  const { client } = createDatabase(databaseUrl);
  const app = await NestFactory.create(AppModule, { logger: false }); app.setGlobalPrefix('v1'); await app.listen(0, '127.0.0.1');
  const apiAddress = app.getHttpServer().address(); assert.ok(apiAddress && typeof apiAddress === 'object'); const base = `http://127.0.0.1:${apiAddress.port}`;
  try {
    await client`TRUNCATE offering_versions, offerings, listing_revisions, listings, provider_property_relationships, properties, provider_accounts, provider_profiles, phone_contacts, security_sessions, auth_identities, users RESTART IDENTITY CASCADE`;
    const users = await client`INSERT INTO users (account_state) VALUES ('ACTIVE'), ('ACTIVE'), ('PENDING_PHONE'), ('ACTIVE') RETURNING id`;
    const first = users[0]; const second = users[1]; const pending = users[2]; const restrictedUser = users[3]; assert.ok(first && second && pending && restrictedUser);
    await client`INSERT INTO phone_contacts (user_id, normalized_e164, verified_at, verification_version) VALUES (${first.id}, '+237690000010', now(), 1), (${second.id}, '+237690000011', now(), 1), (${restrictedUser.id}, '+237690000012', now(), 1)`;
    await client`INSERT INTO auth_identities (user_id, issuer, subject, provider) VALUES (${first.id}, ${issuer}, ${first.id}, 'LOCAL_TEST'), (${second.id}, ${issuer}, ${second.id}, 'LOCAL_TEST'), (${pending.id}, ${issuer}, ${pending.id}, 'LOCAL_TEST'), (${restrictedUser.id}, ${issuer}, ${restrictedUser.id}, 'LOCAL_TEST')`;
    await client`INSERT INTO provider_profiles (user_id, provider_types, display_name, state, verification_status) VALUES (${first.id}, ARRAY['OWNER'], 'First Provider', 'DRAFT', 'NOT_VERIFIED'), (${second.id}, ARRAY['OWNER'], 'Second Provider', 'DRAFT', 'NOT_VERIFIED'), (${restrictedUser.id}, ARRAY['OWNER'], 'Restricted Provider', 'RESTRICTED', 'NOT_VERIFIED')`;
    await client`INSERT INTO provider_accounts (provider_profile_id) SELECT id FROM provider_profiles ORDER BY created_at`;
    const token = async (subject: string, family: string) => new SignJWT({ client_id: 'property-test-client', origin_jti: family, jti: `${family}-token`, token_use: 'access', scope: 'pachi/account' }).setProtectedHeader({ alg: 'RS256', kid: 'property-test-key' }).setIssuer(issuer).setSubject(subject).setIssuedAt().setExpirationTime('5m').sign(privateKey);
    const firstToken = await token(first.id, 'property-first'); const secondToken = await token(second.id, 'property-second'); const pendingToken = await token(pending.id, 'property-pending'); const restrictedToken = await token(restrictedUser.id, 'property-restricted');
    const post = (path: string, accessToken: string, body: unknown) => fetch(`${base}${path}`, { method: 'POST', headers: { authorization: `Bearer ${accessToken}`, 'content-type': 'application/json' }, body: JSON.stringify(body) });
    const propertyResponse = await post('/v1/account/properties', firstToken, { property_type: 'APARTMENT', region: 'Littoral', city: 'Douala', neighborhood: 'Bonanjo', relationship_type: 'OWNER' });
    assert.equal(propertyResponse.status, 201); const property = await propertyResponse.json() as { id: string; relationship_id: string; version: number };
    assert.equal(property.version, 1);
    assert.notEqual(property.id, property.relationship_id); const declarationRows = await client`SELECT relationship_type, authorization_status FROM provider_property_relationships WHERE id = ${property.relationship_id} AND property_id = ${property.id}`; assert.deepEqual(Array.from(declarationRows), [{ relationship_type: 'OWNER', authorization_status: 'DECLARED' }]);
    const propertyRetry = await post('/v1/account/properties', firstToken, { property_type: 'APARTMENT', region: 'Littoral', city: 'Douala', neighborhood: 'Bonanjo', relationship_type: 'OWNER' });
    assert.equal(propertyRetry.status, 201); const propertyList = await fetch(`${base}/v1/account/properties`, { headers: { authorization: `Bearer ${firstToken}` } }); assert.equal(propertyList.status, 200); const propertyListBody = await propertyList.json() as { properties: unknown[] }; assert.equal(propertyListBody.properties.length, 2);
    const draftResponse = await post('/v1/account/listing-drafts', firstToken, { property_id: property.id, purpose: 'RENT', title: 'Draft home', description: 'Initial details', amount_minor: 250000, pricing_period: 'MONTHLY', negotiable: true, deposit_amount_minor: 250000, advance_months: 2, minimum_lease_months: 6, utilities_included: false, service_charge_amount_minor: 12000, available_from: '2026-10-01' });
    assert.equal(draftResponse.status, 201); const draft = await draftResponse.json() as { id: string; property_id: string; publication_status: string; currency: string; version: number };
    assert.equal(draft.publication_status, 'DRAFT'); assert.equal(draft.currency, 'XAF'); assert.equal(draft.property_id, property.id);
    const readinessResponse = await fetch(`${base}/v1/account/listing-drafts/${draft.id}/readiness`, { headers: { authorization: `Bearer ${firstToken}` } }); const readiness = await readinessResponse.json() as { can_submit: boolean; publication_status: string; revision_id: string; offering_version_id: string; checks: Array<{ code: string; status: string }> }; assert.equal(readinessResponse.status, 200); assert.equal(readiness.can_submit, false); assert.equal(readiness.publication_status, 'DRAFT'); assert.ok(readiness.checks.some((check) => check.code === 'MEDIA_REQUIRED' && check.status === 'BLOCKED')); assert.ok(readiness.checks.some((check) => check.code === 'MEDIA_CONTENT_APPROVAL_REQUIRED' && check.status === 'BLOCKED')); assert.ok(readiness.checks.some((check) => check.code === 'PROVIDER_IDENTITY_VERIFICATION_UNAVAILABLE' && check.status === 'BLOCKED')); assert.ok(readiness.checks.some((check) => check.code === 'PROPERTY_RISK_HOLD_EVALUATION_UNAVAILABLE' && check.status === 'BLOCKED'));
    const profileUpdate = await post('/v1/account/provider/onboard', firstToken, { provider_types: ['OWNER'], display_name: 'Updated First Provider', bio: 'Public profile', service_area: 'Douala' });
    assert.equal(profileUpdate.status, 201);
    const readinessAfterProfileEdit = await (await fetch(`${base}/v1/account/listing-drafts/${draft.id}/readiness`, { headers: { authorization: `Bearer ${firstToken}` } })).json() as typeof readiness;
    assert.equal(readinessAfterProfileEdit.can_submit, false);
    assert.ok(readinessAfterProfileEdit.checks.some(check => check.code === 'PROVIDER_NOT_ACTIVE' && check.status === 'BLOCKED'));
    assert.ok(readinessAfterProfileEdit.checks.some(check => check.code === 'PROVIDER_IDENTITY_VERIFICATION_UNAVAILABLE' && check.status === 'BLOCKED'));
    assert.ok(readinessAfterProfileEdit.checks.some(check => check.code === 'PROPERTY_RISK_HOLD_EVALUATION_UNAVAILABLE' && check.status === 'BLOCKED'));
    assert.ok(readinessAfterProfileEdit.checks.some(check => check.code === 'PROPERTY_SPECIFICATION_REQUIRED' && check.status === 'BLOCKED'));
    const patchSpecifications = (accessToken: string, body: unknown) => fetch(`${base}/v1/account/properties/${property.id}/specifications`, { method: 'PATCH', headers: { authorization: `Bearer ${accessToken}`, 'content-type': 'application/json' }, body: JSON.stringify(body) });
    assert.equal((await fetch(`${base}/v1/account/properties/${property.id}/specifications`, { method: 'PATCH', headers: { authorization: `Bearer ${firstToken}` } })).status, 409);
    assert.equal((await patchSpecifications(secondToken, { expected_version: 1, bedrooms: 3 })).status, 404);
    assert.equal((await patchSpecifications(firstToken, { expected_version: 1, bedrooms: -1 })).status, 409);
    assert.equal((await patchSpecifications(firstToken, { expected_version: 1, furnishing: 'UNREVIEWED' })).status, 409);
    assert.equal((await patchSpecifications(firstToken, { expected_version: 1, bedrooms: '3' })).status, 409);
    const savedSpecifications = await patchSpecifications(firstToken, { expected_version: 1, bedrooms: 2, size_sqm: 85.5, furnishing: 'FURNISHED' });
    assert.equal(savedSpecifications.status, 200);
    const savedProperty = await savedSpecifications.json() as { version: number; bedrooms: number; size_sqm: string; furnishing: string; property_type: string };
    assert.deepEqual([savedProperty.version, savedProperty.bedrooms, savedProperty.size_sqm, savedProperty.furnishing, savedProperty.property_type], [2, 2, '85.5', 'FURNISHED', 'APARTMENT']);
    const reloadedProperties = await (await fetch(`${base}/v1/account/properties`, { headers: { authorization: `Bearer ${firstToken}` } })).json() as { properties: Array<{ id: string; version: number; bedrooms: number }> };
    assert.deepEqual([reloadedProperties.properties.find(item => item.id === property.id)?.version, reloadedProperties.properties.find(item => item.id === property.id)?.bedrooms], [2, 2]);
    const readinessAfterSpecifications = await (await fetch(`${base}/v1/account/listing-drafts/${draft.id}/readiness`, { headers: { authorization: `Bearer ${firstToken}` } })).json() as typeof readiness;
    assert.ok(readinessAfterSpecifications.checks.some(check => check.code === 'PROPERTY_SPECIFICATION_REQUIRED' && check.status === 'READY'));
    assert.ok(readinessAfterSpecifications.checks.some(check => check.code === 'PROVIDER_NOT_ACTIVE' && check.status === 'BLOCKED'));
    assert.ok(readinessAfterSpecifications.checks.some(check => check.code === 'PROVIDER_IDENTITY_VERIFICATION_UNAVAILABLE' && check.status === 'BLOCKED'));
    assert.ok(readinessAfterSpecifications.checks.some(check => check.code === 'PROPERTY_RISK_HOLD_EVALUATION_UNAVAILABLE' && check.status === 'BLOCKED'));
    assert.equal(readinessAfterSpecifications.can_submit, false);
    assert.equal((await patchSpecifications(firstToken, { expected_version: 1, bathrooms: 1 })).status, 409);
    assert.equal((await patchSpecifications(firstToken, { expected_version: 2, property_type: 'COMMERCIAL', publication_status: 'PUBLISHED', verification_status: 'VERIFIED' })).status, 409);
    await client`UPDATE listings SET publication_status='PENDING_REVIEW' WHERE id=${draft.id}`;
    assert.equal((await patchSpecifications(firstToken, { expected_version: 2, bathrooms: 1 })).status, 409);
    await client`UPDATE listings SET publication_status='DRAFT' WHERE id=${draft.id}`;
    const clearedSpecifications = await patchSpecifications(firstToken, { expected_version: 2, bedrooms: null, size_sqm: null, furnishing: null });
    assert.equal(clearedSpecifications.status, 200);
    assert.equal((await clearedSpecifications.json() as { version: number }).version, 3);
    const readinessAfterClearing = await (await fetch(`${base}/v1/account/listing-drafts/${draft.id}/readiness`, { headers: { authorization: `Bearer ${firstToken}` } })).json() as typeof readiness;
    assert.ok(readinessAfterClearing.checks.some(check => check.code === 'PROPERTY_SPECIFICATION_REQUIRED' && check.status === 'BLOCKED'));
    const verificationStore = new ProviderVerificationStore(client,'synthetic-readiness-evidence-secret-long-enough',true);
    const verificationCase = await verificationStore.submit(first.id,{idempotencyKey:`readiness_${randomUUID()}`,capacity:'OWNER',governmentId:'PACHI_SYNTHETIC_GOVERNMENT_ID_V1',liveSelfie:'PACHI_SYNTHETIC_LIVE_SELFIE_V1',requestId:randomUUID(),syntheticEnabled:true});
    const officerScope = {kind:'case' as const,id:verificationCase.id,permissions:['provider:verify','evidence:read']};
    await client`INSERT INTO staff_grants(user_id,role,permission_scope,expires_at,granted_by,reason) VALUES (${second.id},'VERIFICATION_OFFICER',${JSON.stringify(officerScope)}::jsonb,now()+interval '1 day','test','readiness decision fixture')`;
    await client`UPDATE verification_cases SET assigned_staff_user_id=${second.id},version=2 WHERE id=${verificationCase.id}`;
    const officer = {row:{user_id:second.id,authenticated_at:new Date()},grants:[{role:'VERIFICATION_OFFICER',scope:officerScope}]} as unknown as StaffPrincipal;
    await verificationStore.evidence(officer,verificationCase.id,'GOVERNMENT_ID',randomUUID()); await verificationStore.evidence(officer,verificationCase.id,'LIVE_SELFIE',randomUUID());
    await verificationStore.decide(officer,verificationCase.id,{expectedVersion:2,outcome:'VERIFIED',reasonCode:'EVIDENCE_ACCEPTED',requestId:randomUUID()});
    const verifiedReadiness = await (await fetch(`${base}/v1/account/listing-drafts/${draft.id}/readiness`, { headers: { authorization: `Bearer ${firstToken}` } })).json() as typeof readiness;
    assert.ok(verifiedReadiness.checks.some(check => check.code==='PROVIDER_IDENTITY_VERIFICATION_UNAVAILABLE' && check.status==='READY'));
    assert.ok(verifiedReadiness.checks.some(check => check.code==='MEDIA_CONTENT_APPROVAL_REQUIRED' && check.status==='BLOCKED'));
    assert.equal(verifiedReadiness.can_submit,false);
    await client`UPDATE verification_claims SET valid_until=now()-interval '1 second' WHERE source_case_id=${verificationCase.id}`;
    const expiredReadiness = await (await fetch(`${base}/v1/account/listing-drafts/${draft.id}/readiness`, { headers: { authorization: `Bearer ${firstToken}` } })).json() as typeof readiness;
    assert.ok(expiredReadiness.checks.some(check => check.code==='PROVIDER_IDENTITY_VERIFICATION_UNAVAILABLE' && check.status==='BLOCKED'));
    await client`UPDATE provider_property_relationships SET authorization_status = 'PENDING' WHERE id = ${property.relationship_id}`;
    const pendingReadinessResponse = await fetch(`${base}/v1/account/listing-drafts/${draft.id}/readiness`, { headers: { authorization: `Bearer ${firstToken}` } }); const pendingReadiness = await pendingReadinessResponse.json() as { checks: Array<{ code: string; status: string }> }; assert.equal(pendingReadinessResponse.status, 200); assert.ok(pendingReadiness.checks.some((check) => check.code === 'PROPERTY_AUTHORITY_REVIEW_UNAVAILABLE' && check.status === 'BLOCKED')); assert.ok(pendingReadiness.checks.some((check) => check.code === 'PROPERTY_RELATIONSHIP_NOT_CURRENT' && check.status === 'BLOCKED'));
    await client`UPDATE provider_property_relationships SET authorization_status = 'DECLARED' WHERE id = ${property.relationship_id}`;
    const crossReadiness = await fetch(`${base}/v1/account/listing-drafts/${draft.id}/readiness`, { headers: { authorization: `Bearer ${secondToken}` } }); assert.equal(crossReadiness.status, 404);
    const blockedSubmission = await fetch(`${base}/v1/account/listing-drafts/${draft.id}/submissions`, { method: 'POST', headers: { authorization: `Bearer ${firstToken}`, 'content-type': 'application/json', 'idempotency-key': 'property-blocked-submission-1' }, body: JSON.stringify({ revision_id: readiness.revision_id, offering_version_id: readiness.offering_version_id }) }); const blockedBody = await blockedSubmission.json() as { submitted: boolean; readiness: { publication_status: string; can_submit: boolean } }; assert.equal(blockedSubmission.status, 422); assert.equal(blockedBody.submitted, false); assert.equal(blockedBody.readiness.can_submit, false); assert.equal(blockedBody.readiness.publication_status, 'DRAFT'); const unchangedSubmissionRows = await client`SELECT count(*)::int AS count FROM listing_submissions WHERE listing_id = ${draft.id}`; assert.equal(unchangedSubmissionRows[0]?.count, 0);
    const staleSubmission = await fetch(`${base}/v1/account/listing-drafts/${draft.id}/submissions`, { method: 'POST', headers: { authorization: `Bearer ${firstToken}`, 'content-type': 'application/json', 'idempotency-key': 'property-stale-submission-1' }, body: JSON.stringify({ revision_id: '00000000-0000-4000-8000-000000000000', offering_version_id: readiness.offering_version_id }) }); assert.equal(staleSubmission.status, 409);
    const reopenedResponse = await fetch(`${base}/v1/account/listing-drafts/${draft.id}`, { headers: { authorization: `Bearer ${firstToken}` } }); assert.equal(reopenedResponse.status, 200); const reopened = await reopenedResponse.json() as { title: string; description: string; amount_minor: number; pricing_period: string; negotiable: boolean; deposit_amount_minor: number; advance_months: number; minimum_lease_months: number; utilities_included: boolean; service_charge_amount_minor: number; available_from: string }; assert.deepEqual([reopened.title, reopened.description, reopened.amount_minor, reopened.pricing_period, reopened.negotiable, reopened.deposit_amount_minor, reopened.advance_months, reopened.minimum_lease_months, reopened.utilities_included, reopened.service_charge_amount_minor, reopened.available_from], ['Draft home', 'Initial details', 250000, 'MONTHLY', true, 250000, 2, 6, false, 12000, '2026-10-01']);
    const retryDraft = await post('/v1/account/listing-drafts', firstToken, { property_id: property.id, purpose: 'RENT', title: 'Draft home', amount_minor: 250000 }); assert.equal(retryDraft.status, 201);
    const shortLetResponse = await post('/v1/account/listing-drafts', firstToken, { property_id: property.id, purpose: 'SHORT_LET', amount_minor: 50000, weekly_amount_minor: 300000, minimum_nights: 2, guest_limit: 4, check_in_time: '14:00', check_out_time: '11:00', cleaning_fee_minor: 10000 }); assert.equal(shortLetResponse.status, 201); const shortLet = await shortLetResponse.json() as { weekly_amount_minor: number; minimum_nights: number; guest_limit: number; check_in_time: string; check_out_time: string; cleaning_fee_minor: number }; assert.deepEqual([shortLet.weekly_amount_minor, shortLet.minimum_nights, shortLet.guest_limit, shortLet.check_in_time, shortLet.check_out_time, shortLet.cleaning_fee_minor], [300000, 2, 4, '14:00:00', '11:00:00', 10000]);
    const invalidTerms = await post('/v1/account/listing-drafts', firstToken, { property_id: property.id, purpose: 'SALE', amount_minor: 80000000, deposit_amount_minor: 1000 }); assert.equal(invalidTerms.status, 409);
    const update = await fetch(`${base}/v1/account/listing-drafts/${draft.id}`, { method: 'PATCH', headers: { authorization: `Bearer ${firstToken}`, 'content-type': 'application/json' }, body: JSON.stringify({ title: 'Updated draft', description: 'Revised details', amount_minor: 275000, deposit_amount_minor: 300000, service_charge_amount_minor: 15000, negotiable: false }) }); assert.equal(update.status, 200); const updated = await update.json() as { title: string; description: string; amount_minor: number; deposit_amount_minor: number; service_charge_amount_minor: number; negotiable: boolean; version: number }; assert.deepEqual([updated.title, updated.description, updated.amount_minor, updated.deposit_amount_minor, updated.service_charge_amount_minor, updated.negotiable, updated.version], ['Updated draft', 'Revised details', 275000, 300000, 15000, false, 2]);
    const reload = await fetch(`${base}/v1/account/listing-drafts`, { headers: { authorization: `Bearer ${firstToken}` } }); assert.equal(reload.status, 200); const reloadBody = await reload.json() as { drafts: Array<{ id: string; title: string | null; description: string | null; amount_minor: number | null; deposit_amount_minor: number | null; service_charge_amount_minor: number | null; negotiable: boolean; version: number }> }; assert.equal(reloadBody.drafts.length, 3); const persisted = reloadBody.drafts.find((item) => item.id === draft.id); assert.deepEqual(persisted && [persisted.title, persisted.description, persisted.amount_minor, persisted.deposit_amount_minor, persisted.service_charge_amount_minor, persisted.negotiable, persisted.version], ['Updated draft', 'Revised details', 275000, 300000, 15000, false, 2]);
    const clearOptional = await fetch(`${base}/v1/account/listing-drafts/${draft.id}`, { method: 'PATCH', headers: { authorization: `Bearer ${firstToken}`, 'content-type': 'application/json' }, body: JSON.stringify({ description: '', deposit_amount_minor: null }) }); assert.equal(clearOptional.status, 200); const cleared = await clearOptional.json() as { description: string | null; deposit_amount_minor: number | null; version: number }; assert.deepEqual([cleared.description, cleared.deposit_amount_minor, cleared.version], [null, null, 3]);
    const cross = await fetch(`${base}/v1/account/listing-drafts`, { headers: { authorization: `Bearer ${secondToken}` } }); assert.equal(cross.status, 200); const crossBody = await cross.json() as { drafts: unknown[] }; assert.equal(crossBody.drafts.length, 0);
    const crossRead = await fetch(`${base}/v1/account/listing-drafts/${draft.id}`, { headers: { authorization: `Bearer ${secondToken}` } }); assert.equal(crossRead.status, 404);
    const crossUpdate = await fetch(`${base}/v1/account/listing-drafts/${draft.id}`, { method: 'PATCH', headers: { authorization: `Bearer ${secondToken}`, 'content-type': 'application/json' }, body: JSON.stringify({ title: 'Tampered' }) }); assert.equal(crossUpdate.status, 409);
    const invalid = await post('/v1/account/properties', firstToken, { property_type: 'INVALID', region: 'Littoral', city: 'Douala', neighborhood: 'Bonanjo', relationship_type: 'OWNER' }); assert.equal(invalid.status, 409);
    const restricted = await post('/v1/account/properties', pendingToken, { property_type: 'HOUSE', region: 'Littoral', city: 'Douala', neighborhood: 'Akwa', relationship_type: 'OWNER' }); assert.equal(restricted.status, 409);
    const restrictedProvider = await post('/v1/account/properties', restrictedToken, { property_type: 'HOUSE', region: 'Littoral', city: 'Douala', neighborhood: 'Akwa', relationship_type: 'OWNER' }); assert.equal(restrictedProvider.status, 409);
    const restrictedReads = await Promise.all([fetch(`${base}/v1/account/properties`, { headers: { authorization: `Bearer ${restrictedToken}` } }), fetch(`${base}/v1/account/listing-drafts`, { headers: { authorization: `Bearer ${restrictedToken}` } })]); assert.deepEqual(restrictedReads.map((response) => response.status), [409, 409]);
  } finally {
    await client`TRUNCATE offering_versions, offerings, listing_revisions, listings, provider_property_relationships, properties, provider_accounts, provider_profiles, phone_contacts, security_sessions, auth_identities, users RESTART IDENTITY CASCADE`;
    await client.end(); await app.close(); await authDatabaseClient.end(); await new Promise<void>((resolve) => jwksServer.close(() => resolve()));
  }
});
