'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import type { PublicListing } from '@pachi/contracts';

export default function PublicListingDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [listing, setListing] = useState<PublicListing | null>(null);
  const [state, setState] = useState<'loading' | 'ready' | 'missing'>('loading');
  useEffect(() => { void params.then(({ id }) => fetch(`/api/public/listings/${encodeURIComponent(id)}`, { cache: 'no-store' }).then(async (response) => { if (!response.ok) throw new Error(); return response.json() as Promise<PublicListing>; }).then((value) => { setListing(value); setState('ready'); }).catch(() => setState('missing'))); }, [params]);
  if (state === 'loading') return <main className="publicShell"><p className="publicState">Loading listing…</p></main>;
  if (state === 'missing' || !listing) return <main className="publicShell"><Link className="backLink" href="/listings">← Back to listings</Link><section className="emptyResults"><h1>This listing is no longer available.</h1><p>It may have expired or changed status. Browse current listings to find another match.</p></section></main>;
  return <main className="publicShell"><Link className="backLink" href="/listings">← Back to listings</Link><article className="detailPage"><header className="detailHeader"><p className="listingKicker">{listing.purpose} · {listing.property.property_type}</p><h1>{listing.title}</h1><p className="listingPrice">{listing.price.amount_minor.toLocaleString()} {listing.price.currency} <span>/ {listing.price.pricing_period.toLowerCase()}</span></p><p className="listingLocation">{listing.location.city}{listing.location.neighborhood ? ` · ${listing.location.neighborhood}` : ''}</p></header><div className="detailGallery">{listing.media.map((media) => <img key={media.id} src={`/api/public/listings/${listing.id}/media/${media.id}/variants/${media.widths.includes(640) ? 640 : media.widths[0] ?? 320}`} alt="" />)}</div><div className="detailGrid"><section className="detailSection"><h2>About this listing</h2><p>{listing.description}</p><dl className="factList"><div><dt>Bedrooms</dt><dd>{listing.property.bedrooms ?? 'Not specified'}</dd></div><div><dt>Bathrooms</dt><dd>{listing.property.bathrooms ?? 'Not specified'}</dd></div><div><dt>Furnishing</dt><dd>{listing.property.furnishing?.toLowerCase().replaceAll('_', ' ') ?? 'Not specified'}</dd></div><div><dt>Available from</dt><dd>{listing.available_from ?? 'Contact provider for timing'}</dd></div></dl></section><section className="detailSection locationPanel"><h2>Location</h2><p>{listing.location.city}</p>{listing.location.neighborhood && <p>{listing.location.neighborhood}</p>}<p>{listing.location.region}</p><small>Structured neighborhood location. No exact address is shown.</small></section></div></article></main>;
}
