import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import { createDatabase } from './client.js';
import { ListingMediaStore } from './listing-media.js';
import { ListingPhotoReviewStore } from './listing-photo-review.js';
import { ListingSubmissionStore } from './listing-submission.js';
import { PropertyDraftStore } from './property.js';
import type { StaffPrincipal } from './staff.js';
import type { StaffScope } from './staff-policy.js';

if (!process.env.DATABASE_TEST_URL && process.env.CI === 'true') throw new Error('DATABASE_TEST_URL is required');
const integration = process.env.DATABASE_TEST_URL ? test : test.skip;

void integration('scoped photo review is separate from processing, versioned, private and bound to the current association', async () => {
  const url = process.env.DATABASE_TEST_URL!;
  const parsed = new URL(url);
  assert.equal(`${parsed.hostname}:${parsed.port}${parsed.pathname}`, 'localhost:5433/pachi_test');
  const { client } = createDatabase(url);
  const properties = new PropertyDraftStore(client);
  const media = new ListingMediaStore(client);
  const reviews = new ListingPhotoReviewStore(client);
  const submissions = new ListingSubmissionStore(client);
  const syntheticSubmissions = new ListingSubmissionStore(client, true);
  try {
    await client`TRUNCATE users RESTART IDENTITY CASCADE`;
    const users = await client<{id:string}[]>`INSERT INTO users(account_state) VALUES ('ACTIVE'),('ACTIVE'),('ACTIVE'),('ACTIVE') RETURNING id`;
    const [owner, moderator, outsider, admin] = users;
    assert.ok(owner && moderator && outsider && admin);
    await client`INSERT INTO phone_contacts(user_id,normalized_e164,verified_at,verification_version) VALUES (${owner.id},'+237690001001',now(),1)`;
    const profile = await client<{id:string}[]>`INSERT INTO provider_profiles(user_id,provider_types,display_name,state,verification_status) VALUES (${owner.id},ARRAY['OWNER'],'Review Fixture','ACTIVE','VERIFIED') RETURNING id`;
    const account = await client<{id:string}[]>`INSERT INTO provider_accounts(provider_profile_id,state) VALUES (${profile[0]!.id},'ACTIVE') RETURNING id`;
    const property = await properties.createProperty(owner.id,{propertyType:'APARTMENT',region:'Littoral',city:'Douala',neighborhood:'Akwa',bedrooms:2,relationshipType:'OWNER'});
    const draft = await properties.createDraft(owner.id,{propertyId:property.id,purpose:'RENT',title:'Review fixture',description:'A complete draft for photo review',amountMinor:200000,availableFrom:'2026-10-01'});
    const syntheticCase = await client<{id:string}[]>`INSERT INTO verification_cases(provider_profile_id,applicant_user_id,verification_type,state,policy_version,idempotency_key,submitted_at,valid_until) VALUES (${profile[0]!.id},${owner.id},'PROVIDER_IDENTITY','VERIFIED','provider-identity-synthetic-v1',${randomUUID()},now(),now()+interval '1 year') RETURNING id`;
    await client`INSERT INTO verification_claims(provider_profile_id,claim_type,status,source_case_id,valid_from,valid_until) VALUES (${profile[0]!.id},'PROVIDER_IDENTITY','VERIFIED',${syntheticCase[0]!.id},now(),now()+interval '1 year')`;
    const makePhoto = async (order: number) => {
      const asset = await client<{id:string}[]>`INSERT INTO media_assets(owner_provider_account_id,classification,storage_reference,lifecycle,original_mime,original_bytes,derivative_manifest) VALUES (${account[0]!.id},'PUBLIC_MARKETPLACE',${randomUUID()},'READY','image/png',128,${JSON.stringify({320:{mime:'image/webp',width:8,height:6,bytes:80}})}::jsonb) RETURNING id`;
      const association = await client<{id:string}[]>`INSERT INTO listing_media(listing_id,media_asset_id,display_order,is_cover,attached_by_user_id) VALUES (${draft.id},${asset[0]!.id},${order},${order===0},${owner.id}) RETURNING id`;
      return { id:association[0]!.id, assetId:asset[0]!.id };
    };
    const first = await makePhoto(0);
    const scope = {kind:'region' as const,id:'Littoral',permissions:['listing:moderate']};
    const grant = await client<{id:string}[]>`INSERT INTO staff_grants(user_id,role,permission_scope,expires_at,granted_by,reason) VALUES (${moderator.id},'LISTING_MODERATOR',${JSON.stringify(scope)}::jsonb,now()+interval '1 day','test','isolated photo review') RETURNING id`;
    const principal = (userId:string, role:string, staffScope: StaffScope, authenticatedAt=new Date()) => ({row:{user_id:userId,authenticated_at:authenticatedAt},grants:[{role,scope:staffScope}]} as unknown as StaffPrincipal);
    const staff = principal(moderator.id,'LISTING_MODERATOR',scope);
    const unrelated = principal(outsider.id,'LISTING_MODERATOR',{...scope,id:'Southwest'});
    const superAdmin = principal(admin.id,'SUPER_ADMIN',{kind:'platform',id:'pachi',permissions:['admin:permissions_manage']});
    const self = principal(owner.id,'LISTING_MODERATOR',scope);
    assert.equal((await reviews.queue(staff)).length,1);
    assert.deepEqual(await reviews.queue(unrelated),[]);
    assert.deepEqual(await reviews.queue(superAdmin),[]);
    await assert.rejects(reviews.preview(unrelated,first.id,320,randomUUID(),async()=>Buffer.from('synthetic-preview')),{code:'RESOURCE_SCOPE_DENIED'});
    await assert.rejects(reviews.preview(superAdmin,first.id,320,randomUUID(),async()=>Buffer.from('synthetic-preview')),{code:'RESOURCE_SCOPE_DENIED'});
    await assert.rejects(reviews.preview(self,first.id,320,randomUUID(),async()=>Buffer.from('synthetic-preview')),{code:'RESOURCE_SCOPE_DENIED'});
    await assert.rejects(reviews.decide(staff,first.id,{mediaAssetId:first.assetId,expectedVersion:1,outcome:'APPROVED',reasonCode:'CONTENT_REVIEWED',requestId:randomUUID(),idempotencyKey:randomUUID()}),{code:'EVIDENCE_REVIEW_REQUIRED'});
    await assert.rejects(reviews.preview(principal(moderator.id,'LISTING_MODERATOR',scope,new Date(Date.now()-16*60_000)),first.id,320,randomUUID(),async()=>Buffer.from('synthetic-preview')),{code:'STEP_UP_REQUIRED'});
    await assert.rejects(reviews.preview(staff,first.id,320,randomUUID(),async()=>{throw new Error('private variant missing');}),/private variant missing/);
    assert.equal((await client`SELECT count(*)::int AS count FROM audit_events WHERE target_id=${first.id} AND action='LISTING_PHOTO_PREVIEW_ACCESSED'`)[0]?.count,0);
    const preview = await reviews.preview(staff,first.id,320,randomUUID(),async()=>Buffer.from('synthetic-preview'));
    assert.equal(preview.mime,'image/webp');
    await assert.rejects(reviews.decide(staff,first.id,{mediaAssetId:randomUUID(),expectedVersion:1,outcome:'APPROVED',reasonCode:'CONTENT_REVIEWED',requestId:randomUUID(),idempotencyKey:randomUUID()}),{code:'STALE_VERSION'});
    const before = await submissions.readiness(owner.id,draft.id);
    assert.equal(before.checks.find(c=>c.code==='MEDIA_CONTENT_APPROVAL_REQUIRED')?.status,'BLOCKED');
    assert.equal(before.checks.find(c=>c.code==='PROVIDER_IDENTITY_VERIFICATION_UNAVAILABLE')?.status,'BLOCKED');
    assert.equal((await syntheticSubmissions.readiness(owner.id,draft.id)).checks.find(c=>c.code==='PROVIDER_IDENTITY_VERIFICATION_UNAVAILABLE')?.status,'READY');
    const outcome = await Promise.allSettled([1,2].map(() => reviews.decide(staff,first.id,{mediaAssetId:first.assetId,expectedVersion:1,outcome:'APPROVED',reasonCode:'CONTENT_REVIEWED',requestId:randomUUID(),idempotencyKey:randomUUID()})));
    assert.deepEqual(outcome.map(result=>result.status).sort(),['fulfilled','rejected']);
    assert.equal((await media.media(owner.id,draft.id))[0]?.reviewStatus,'APPROVED');
    const ready = await submissions.readiness(owner.id,draft.id);
    assert.equal(ready.checks.find(c=>c.code==='MEDIA_CONTENT_APPROVAL_REQUIRED')?.status,'READY');
    assert.equal(ready.checks.find(c=>c.code==='PROVIDER_IDENTITY_VERIFICATION_UNAVAILABLE')?.status,'BLOCKED');
    assert.equal(ready.canSubmit,false);
    assert.equal((await client`SELECT count(*)::int AS count FROM listing_photo_review_actions WHERE listing_media_id=${first.id}`)[0]?.count,1);
    assert.equal((await client`SELECT count(*)::int AS count FROM listing_photo_review_outbox`)[0]?.count,1);
    await media.remove(owner.id,draft.id,first.assetId);
    const replacement = await makePhoto(0);
    const replaced = await submissions.readiness(owner.id,draft.id);
    assert.equal(replaced.checks.find(c=>c.code==='MEDIA_CONTENT_APPROVAL_REQUIRED')?.status,'BLOCKED');
    await assert.rejects(reviews.decide(staff,first.id,{mediaAssetId:first.assetId,expectedVersion:2,outcome:'APPROVED',reasonCode:'CONTENT_REVIEWED',requestId:randomUUID(),idempotencyKey:randomUUID()}),{code:'INVALID_STATE'});
    await assert.rejects(reviews.decide(staff,replacement.id,{mediaAssetId:first.assetId,expectedVersion:1,outcome:'APPROVED',reasonCode:'CONTENT_REVIEWED',requestId:randomUUID(),idempotencyKey:randomUUID()}),{code:'STALE_VERSION'});
    await reviews.preview(staff,replacement.id,320,randomUUID(),async()=>Buffer.from('synthetic-preview'));
    const repeatKey = randomUUID();
    const correction = {mediaAssetId:replacement.assetId,expectedVersion:1,outcome:'CHANGES_REQUIRED' as const,reasonCode:'PRIVACY_EXPOSURE',requestId:randomUUID(),idempotencyKey:repeatKey};
    await reviews.decide(staff,replacement.id,correction);
    assert.equal((await reviews.decide(staff,replacement.id,correction)).version,2);
    await assert.rejects(reviews.decide(staff,replacement.id,{...correction,outcome:'REJECTED'}),{code:'IDEMPOTENCY_KEY_REUSED'});
    assert.equal((await client`SELECT count(*)::int AS count FROM listing_photo_review_outbox`)[0]?.count,2);
    assert.equal((await media.media(owner.id,draft.id))[0]?.nextAction,'REPLACE_PHOTO');
    assert.equal((await submissions.readiness(owner.id,draft.id)).checks.find(c=>c.code==='MEDIA_CONTENT_APPROVAL_REQUIRED')?.status,'BLOCKED');
    await client`UPDATE staff_grants SET revoked_at=now() WHERE id=${grant[0]!.id}`;
    assert.deepEqual(await reviews.queue(staff),[]);
    await assert.rejects(reviews.preview(staff,replacement.id,320,randomUUID(),async()=>Buffer.from('synthetic-preview')),{code:'RESOURCE_SCOPE_DENIED'});
    const audits = await client`SELECT action FROM audit_events WHERE target_id IN (${first.id},${replacement.id}) AND action IN ('LISTING_PHOTO_PREVIEW_ACCESSED','LISTING_PHOTO_REVIEW_DECIDED','LISTING_PHOTO_REVIEW_DENIED')`;
    assert.ok(audits.some(a=>a.action==='LISTING_PHOTO_PREVIEW_ACCESSED'));
    assert.ok(audits.some(a=>a.action==='LISTING_PHOTO_REVIEW_DECIDED'));
  } finally {
    await client`TRUNCATE users RESTART IDENTITY CASCADE`;
    await client.end();
  }
});
