import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import { createDatabase } from './client.js';
import { ProviderVerificationStore } from './provider-verification.js';
import type { StaffPrincipal } from './staff.js';

const integration = process.env.DATABASE_TEST_URL ? test : test.skip;
void integration('provider identity case, scoped review, claim and retention', async () => {
  const url = new URL(process.env.DATABASE_TEST_URL!);
  assert.equal(url.hostname,'localhost'); assert.equal(url.port,'5433'); assert.equal(url.pathname,'/pachi_test');
  const {client} = createDatabase(url.toString());
  const store = new ProviderVerificationStore(client,'synthetic-evidence-key-for-isolated-tests');
  const ids: string[] = [];
  const principal = (userId:string, grants: Array<{role:string;scope:{kind:'platform'|'case';id:string;permissions:string[]}}>, authenticatedAt=new Date()) => ({row:{user_id:userId,authenticated_at:authenticatedAt},grants}) as unknown as StaffPrincipal;
  try {
    for (let i=0;i<4;i++) { const rows=await client<{id:string}[]>`INSERT INTO users(account_state) VALUES ('ACTIVE') RETURNING id`; ids.push(rows[0]!.id); }
    const [applicant,officer,admin,other] = ids as [string,string,string,string];
    await client`INSERT INTO phone_contacts(user_id,normalized_e164,verified_at,verification_version) VALUES (${applicant},${`+23769${Math.floor(Math.random()*1e7).toString().padStart(7,'0')}`},now(),1)`;
    const profiles=await client<{id:string}[]>`INSERT INTO provider_profiles(user_id,provider_types,display_name) VALUES (${applicant},ARRAY['OWNER','PROPERTY_MANAGER'],'Synthetic Provider') RETURNING id`;
    const profileId=profiles[0]!.id;
    await client`INSERT INTO provider_accounts(provider_profile_id) VALUES (${profileId})`;
    const input={idempotencyKey:`case_${randomUUID()}`,capacity:'OWNER',governmentId:'PACHI_SYNTHETIC_GOVERNMENT_ID_V1',liveSelfie:'PACHI_SYNTHETIC_LIVE_SELFIE_V1',requestId:randomUUID(),syntheticEnabled:true};
    await assert.rejects(store.submit(applicant,{...input,syntheticEnabled:false}),{code:'EVIDENCE_POLICY_UNAVAILABLE'});
    await assert.rejects(store.submit(applicant,{...input,governmentId:'real-document'}),{code:'EVIDENCE_POLICY_UNAVAILABLE'});
    await assert.rejects(store.submit(other,input),{code:'RESOURCE_SCOPE_DENIED'});
    const first=await store.submit(applicant,input);
    assert.equal(first.state,'PENDING'); assert.equal(first.next_action,'WAIT_FOR_REVIEW');
    assert.equal((await store.submit(applicant,input)).id,first.id);
    await assert.rejects(store.submit(applicant,{...input,capacity:'PROPERTY_MANAGER'}),{code:'IDEMPOTENCY_KEY_REUSED'});
    await assert.rejects(store.submit(applicant,{...input,idempotencyKey:`case_${randomUUID()}`}),{code:'INVALID_STATE'});
    const scope={kind:'case' as const,id:first.id,permissions:['provider:verify','evidence:read']};
    await assert.rejects(store.decide(principal(applicant,[{role:'VERIFICATION_OFFICER',scope}]),first.id,{expectedVersion:1,outcome:'VERIFIED',reasonCode:'EVIDENCE_ACCEPTED',requestId:randomUUID()}),{code:'RESOURCE_SCOPE_DENIED'});
    const scopedGrant=await client<{id:string}[]>`INSERT INTO staff_grants(user_id,role,permission_scope,expires_at,granted_by,reason) VALUES (${officer},'VERIFICATION_OFFICER',${JSON.stringify(scope)}::jsonb,now()+interval '1 day','test','isolated scoped fixture') RETURNING id`;
    const officerPrincipal=principal(officer,[{role:'VERIFICATION_OFFICER',scope}]);
    const adminPrincipal=principal(admin,[{role:'SUPER_ADMIN',scope:{kind:'platform',id:'pachi',permissions:['admin:permissions_manage']}}]);
    await client`INSERT INTO staff_grants(user_id,role,permission_scope,expires_at,granted_by,reason) VALUES (${admin},'SUPER_ADMIN','{"kind":"platform","id":"pachi","permissions":["admin:permissions_manage"]}'::jsonb,now()+interval '1 day','test','isolated assignment fixture')`;
    await assert.rejects(store.assigned(officerPrincipal,first.id),{code:'RESOURCE_SCOPE_DENIED'});
    await assert.rejects(store.decide(adminPrincipal,first.id,{expectedVersion:1,outcome:'VERIFIED',reasonCode:'EVIDENCE_ACCEPTED',requestId:randomUUID()}),{code:'RESOURCE_SCOPE_DENIED'});
    const assigned=await store.assign(adminPrincipal,first.id,officer,1,randomUUID());
    assert.equal(assigned.version,2);
    await assert.rejects(store.assign(adminPrincipal,first.id,other,1,randomUUID()),{code:'STALE_VERSION'});
    await assert.rejects(store.evidence(principal(officer,[{role:'VERIFICATION_OFFICER',scope}],new Date(Date.now()-901_000)),first.id,'GOVERNMENT_ID',randomUUID()),{code:'STEP_UP_REQUIRED'});
    await assert.rejects(store.decide(officerPrincipal,first.id,{expectedVersion:2,outcome:'VERIFIED',reasonCode:'EVIDENCE_ACCEPTED',requestId:randomUUID()}),{code:'EVIDENCE_REVIEW_REQUIRED'});
    assert.equal((await store.evidence(officerPrincipal,first.id,'GOVERNMENT_ID',randomUUID())).content,input.governmentId);
    assert.equal((await store.evidence(officerPrincipal,first.id,'LIVE_SELFIE',randomUUID())).content,input.liveSelfie);
    await client`UPDATE staff_grants SET revoked_at=now() WHERE id=${scopedGrant[0]!.id}`;
    await assert.rejects(store.evidence(officerPrincipal,first.id,'LIVE_SELFIE',randomUUID()),{code:'RESOURCE_SCOPE_DENIED'});
    await client`UPDATE staff_grants SET revoked_at=NULL WHERE id=${scopedGrant[0]!.id}`;
    await assert.rejects(store.evidence(principal(other,[{role:'VERIFICATION_OFFICER',scope}]),first.id,'LIVE_SELFIE',randomUUID()),{code:'RESOURCE_SCOPE_DENIED'});
    await assert.rejects(store.decide(officerPrincipal,first.id,{expectedVersion:2,outcome:'VERIFIED',reasonCode:'DOCUMENT_UNREADABLE',requestId:randomUUID()}),{code:'INVALID_INPUT'});
    const decisions=await Promise.allSettled([store.decide(officerPrincipal,first.id,{expectedVersion:2,outcome:'VERIFIED',reasonCode:'EVIDENCE_ACCEPTED',requestId:randomUUID()}),store.decide(officerPrincipal,first.id,{expectedVersion:2,outcome:'VERIFIED',reasonCode:'EVIDENCE_ACCEPTED',requestId:randomUUID()})]);
    assert.equal(decisions.filter(d=>d.status==='fulfilled').length,1);
    assert.equal(decisions.filter(d=>d.status==='rejected').length,1);
    const caseRow=await client<{state:string;version:number}[]>`SELECT state,version FROM verification_cases WHERE id=${first.id}`;
    assert.equal(caseRow[0]?.version,3);
    const claims=await client<{status:string}[]>`SELECT status FROM verification_claims WHERE provider_profile_id=${profileId}`;
    assert.equal(caseRow[0]?.state,'VERIFIED'); assert.equal(claims[0]?.status,'VERIFIED');
    const decisionsRows=await client<{count:number}[]>`SELECT count(*)::int AS count FROM verification_decisions WHERE case_id=${first.id}`;
    assert.equal(decisionsRows[0]?.count,1);
    const current=await client<{valid:boolean}[]>`SELECT EXISTS(SELECT 1 FROM verification_claims WHERE provider_profile_id=${profileId} AND status='VERIFIED' AND valid_until>now()) AS valid`;
    assert.equal(current[0]?.valid,true);
    await client`UPDATE verification_claims SET valid_until=now()-interval '1 day' WHERE provider_profile_id=${profileId}`;
    await client`UPDATE verification_cases SET valid_until=now()-interval '1 day' WHERE id=${first.id}`;
    assert.equal((await store.own(applicant))?.state,'EXPIRED');
    assert.ok(await store.expireClaims()>=1);
    assert.equal(await store.expireClaims(),0);
    assert.equal((await store.own(applicant))?.state,'EXPIRED');
    const renewal=await store.submit(applicant,{...input,idempotencyKey:`renew_${randomUUID()}`});
    assert.equal(renewal.previous_case_id,first.id);
    const renewalScope={kind:'case' as const,id:renewal.id,permissions:['provider:verify','evidence:read']};
    await client`INSERT INTO staff_grants(user_id,role,permission_scope,expires_at,granted_by,reason) VALUES (${officer},'VERIFICATION_OFFICER',${JSON.stringify(renewalScope)}::jsonb,now()+interval '1 day','test','isolated renewal fixture')`;
    const renewalPrincipal=principal(officer,[{role:'VERIFICATION_OFFICER',scope:renewalScope}]);
    await store.assign(adminPrincipal,renewal.id,officer,1,randomUUID());
    await store.evidence(renewalPrincipal,renewal.id,'GOVERNMENT_ID',randomUUID());
    await store.evidence(renewalPrincipal,renewal.id,'LIVE_SELFIE',randomUUID());
    const correction=await store.decide(renewalPrincipal,renewal.id,{expectedVersion:2,outcome:'NEEDS_RESUBMISSION',reasonCode:'DOCUMENT_UNREADABLE',requestId:randomUUID()});
    assert.equal(correction.next_action,'SUBMIT_CORRECTION');
    const corrected=await store.submit(applicant,{...input,idempotencyKey:`correct_${randomUUID()}`});
    assert.equal(corrected.previous_case_id,renewal.id);
    const correctedScope={kind:'case' as const,id:corrected.id,permissions:['provider:verify','evidence:read']};
    await client`INSERT INTO staff_grants(user_id,role,permission_scope,expires_at,granted_by,reason) VALUES (${officer},'VERIFICATION_OFFICER',${JSON.stringify(correctedScope)}::jsonb,now()+interval '1 day','test','isolated correction fixture')`;
    const correctedPrincipal=principal(officer,[{role:'VERIFICATION_OFFICER',scope:correctedScope}]);
    await store.assign(adminPrincipal,corrected.id,officer,1,randomUUID());
    await store.evidence(correctedPrincipal,corrected.id,'GOVERNMENT_ID',randomUUID());
    await store.evidence(correctedPrincipal,corrected.id,'LIVE_SELFIE',randomUUID());
    const rejection=await store.decide(correctedPrincipal,corrected.id,{expectedVersion:2,outcome:'REJECTED',reasonCode:'SUBJECT_MISMATCH',requestId:randomUUID()});
    assert.equal(rejection.next_action,'SUBMIT_NEW_CASE');
    assert.equal((await store.own(applicant))?.reason_code,'SUBJECT_MISMATCH');
    await assert.rejects(client`UPDATE verification_decisions SET reason_code='OTHER' WHERE case_id=${first.id}`,/append-only/);
    const hold=await client<{id:string}[]>`SELECT id FROM verification_evidence WHERE case_id=${first.id} AND evidence_type='GOVERNMENT_ID'`;
    await assert.rejects(client`UPDATE verification_evidence SET sha256=${'0'.repeat(64)} WHERE id=${hold[0]!.id}`,/immutable/);
    await assert.rejects(client`UPDATE verification_cases SET applicant_user_id=${other} WHERE id=${first.id}`,/immutable/);
    const held=await client<{id:string}[]>`INSERT INTO verification_evidence_holds(evidence_id,reason_code,owner_user_id,review_due_at) VALUES (${hold[0]!.id},'SYNTHETIC_TEST_HOLD',${admin},now()+interval '1 day') RETURNING id`;
    await client`UPDATE verification_evidence SET delete_after=now()-interval '1 day',legal_hold_id=${held[0]!.id} WHERE id=${hold[0]!.id}`;
    await client`UPDATE verification_evidence SET delete_after=now()-interval '1 day' WHERE case_id=${first.id} AND evidence_type='LIVE_SELFIE'`;
    assert.equal(await store.purgeExpiredEvidence(),1);
    const retained=await client<{encrypted_content:Buffer|null;deleted_at:Date|null}[]>`SELECT encrypted_content,deleted_at FROM verification_evidence WHERE id=${hold[0]!.id}`;
    assert.ok(retained[0]?.encrypted_content); assert.equal(retained[0]?.deleted_at,null);
    await client`UPDATE verification_evidence_holds SET released_at=now() WHERE id=${held[0]!.id}`;
    assert.equal(await store.purgeExpiredEvidence(),1);
    assert.equal(await store.purgeExpiredEvidence(),0);
  } finally { await client`TRUNCATE users RESTART IDENTITY CASCADE`; await client.end(); }
});
